name: CI/CD - Pipeline
on: 
  push:
    branches: ['main', 'Sphinx_Docs']

jobs:
  Code-Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Code-Dependencies
        run: |
          pip install -r requirements.txt
          pip install black

      - name: Lint with Black
        run: black pipeline/ --check

  Generating-Documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # One Python version sufficient -> creating, not testing

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Code dependencies
        run: pip install -r requirements.txt

      - name: Install Sphinx & Theme 
        run: pip install sphinx sphinx-rtd-theme

      - name: Generate API Documentation
        working-directory: docs
        run: |
          sphinx-apidoc -f -o . ../pipeline

      - name: Build Docs
        working-directory: docs
        run: |
          sphinx-build -b html . build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          keep_files: false